name: mmazzariol.com
favicon: null
layout_spectrum: 0.39518037298694253
typography_spectrum: 0.10504996660165489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.533595684915781
  lightness: 0.22059063031338155
  saturation: 0.826389160938561
  rhythmicContrast: 0.603711080737412
purpose: []
